version: "3"
volumes:
  db_data:
services:
  app:
    image: cryptotracker
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    command: /start-reload.sh
    environment:
      PORT: "8000"
      DATABASE_URL: postgres://postgres:dev_password@db/cryptotracker
      SENDGRID_API_KEY:
      USE_REAL_MAILER:
      NOTIFY_EMAILS:
      WAIT_FOR_DB: "true"
    ports:
      - 8000:8000
    volumes:
      - .:/app/
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cryptotracker
      POSTGRES_PASSWORD: dev_password
